apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic

spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic

    spec:
      # Pod Security Context 추가
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      containers:
      - name: petclinic
        image: 450444046629.dkr.ecr.us-east-1.amazonaws.com/user01-petclinic:v13
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: MYSQL_URL
          value: jdbc:mysql://petclinic01-rds.co3e28w0ot90.us-east-1.rds.amazonaws.com:3306/petclinic

        - name: MYSQL_USER
          value: master

        - name: MYSQL_PASSWORD
          value: rhgusdn0919

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

        volumeMounts:
        - name: tmp
          mountPath: /tmp

      volumes:
      - name: tmp
        emptyDir: {}
